using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Spectara.Revela.Sdk.Generators;

/// <summary>
/// Source generator that creates IOptions registration extension methods
/// for classes annotated with [RevelaConfig].
/// </summary>
[Generator]
public sealed class ConfigRegistrationGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Spectara.Revela.Sdk.Abstractions.RevelaConfigAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all classes with [RevelaConfig] attribute
        var configClasses = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetConfigInfo(ctx))
            .Where(static info => info != null)
            .Select(static (info, _) => info!);

        // Generate source for each config class
        context.RegisterSourceOutput(configClasses, static (spc, info) =>
        {
            var source = GenerateRegistrationMethod(info);
            spc.AddSource($"{info.ClassName}Registration.g.cs", SourceText.From(source, Encoding.UTF8));
        });

        // Generate a combined registration method for all configs in the assembly
        context.RegisterSourceOutput(configClasses.Collect(), static (spc, configs) =>
        {
            if (configs.IsEmpty)
            {
                return;
            }

            var source = GenerateCombinedRegistration(configs);
            spc.AddSource("RevelaConfigRegistration.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static ConfigInfo? GetConfigInfo(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not INamedTypeSymbol symbol)
        {
            return null;
        }

        var attribute = context.Attributes.FirstOrDefault(a =>
            a.AttributeClass?.ToDisplayString() == AttributeFullName);

        if (attribute == null)
        {
            return null;
        }

        // Get constructor argument: sectionName
        var sectionName = attribute.ConstructorArguments.FirstOrDefault().Value as string;
        if (string.IsNullOrEmpty(sectionName))
        {
            return null;
        }

        // Get named arguments
        var validateDataAnnotations = true;

        foreach (var named in attribute.NamedArguments)
        {
            if (named.Key == "ValidateDataAnnotations")
            {
                validateDataAnnotations = (bool)(named.Value.Value ?? true);
            }
        }

        return new ConfigInfo(
            symbol.ContainingNamespace.ToDisplayString(),
            symbol.Name,
            symbol.ToDisplayString(),
            sectionName!,
            validateDataAnnotations,
            symbol.DeclaredAccessibility);
    }

    private static string GenerateRegistrationMethod(ConfigInfo info)
    {
        var methodAccessibility = info.Accessibility == Accessibility.Public ? "public" : "internal";
        var classAccessibility = info.Accessibility == Accessibility.Public ? "public" : "internal";
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Diagnostics.CodeAnalysis;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine($"namespace {info.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"{classAccessibility} static class {info.ClassName}Registration");
        sb.AppendLine("{");

        // Tell the trimmer to keep public properties of TOptions so that
        // configuration binding (handled by the Configuration source generator)
        // and ValidateDataAnnotations (which still uses reflection) work after
        // PublishTrimmed. DynamicDependency is the documented mechanism when
        // DAM cannot be placed on the type itself.
        sb.AppendLine($"    [DynamicDependency(DynamicallyAccessedMemberTypes.PublicProperties, typeof({info.FullTypeName}))]");

        // BindConfiguration is intercepted by the Configuration source generator
        // (EnableConfigurationBindingGenerator=true). ValidateDataAnnotations
        // still uses reflection — DynamicDependency above preserves the members
        // it inspects, so the suppression is honest.
        sb.AppendLine("    [UnconditionalSuppressMessage(");
        sb.AppendLine("        \"Trimming\",");
        sb.AppendLine("        \"IL2026:Members attributed with RequiresUnreferencedCode may break when trimming\",");
        sb.AppendLine($"        Justification = \"BindConfiguration is replaced by the Configuration source generator. ValidateDataAnnotations preserved members are kept via DynamicDependency on {info.ClassName}.\")]");
        sb.AppendLine("    [UnconditionalSuppressMessage(");
        sb.AppendLine("        \"AOT\",");
        sb.AppendLine("        \"IL3050:Calling members annotated with 'RequiresDynamicCodeAttribute' may break functionality when AOT compiling\",");
        sb.AppendLine($"        Justification = \"BindConfiguration is replaced by the Configuration source generator; no dynamic code is emitted for {info.ClassName}.\")]");
        sb.AppendLine($"    {methodAccessibility} static IServiceCollection Add{info.ClassName}(this IServiceCollection services)");
        sb.AppendLine("    {");
        sb.AppendLine($"        services.AddOptions<{info.FullTypeName}>()");
        sb.Append($"            .BindConfiguration(\"{info.SectionName}\")");

        if (info.ValidateDataAnnotations)
        {
            sb.AppendLine();
            sb.Append("            .ValidateDataAnnotations()");
        }

        sb.AppendLine(";");
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GenerateCombinedRegistration(ImmutableArray<ConfigInfo> configs)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");

        // Add using for each unique namespace
        var namespaces = configs
            .Select(c => c.Namespace)
            .Distinct()
            .OrderBy(n => n, StringComparer.Ordinal);

        foreach (var ns in namespaces)
        {
            sb.AppendLine($"using {ns};");
        }

        sb.AppendLine();
        sb.AppendLine("namespace Spectara.Revela.Sdk.Configuration;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Auto-generated combined registration for all [RevelaConfig] classes in this assembly.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal static class RevelaConfigRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    internal static IServiceCollection AddAllRevelaConfigs(this IServiceCollection services)");
        sb.AppendLine("    {");

        foreach (var config in configs.OrderBy(c => c.ClassName, StringComparer.Ordinal))
        {
            sb.AppendLine($"        services.Add{config.ClassName}();");
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private sealed class ConfigInfo
    {
        public ConfigInfo(
            string ns,
            string className,
            string fullTypeName,
            string sectionName,
            bool validateDataAnnotations,
            Accessibility accessibility)
        {
            Namespace = ns;
            ClassName = className;
            FullTypeName = fullTypeName;
            SectionName = sectionName;
            ValidateDataAnnotations = validateDataAnnotations;
            Accessibility = accessibility;
        }

        public string Namespace { get; }
        public string ClassName { get; }
        public string FullTypeName { get; }
        public string SectionName { get; }
        public bool ValidateDataAnnotations { get; }
        public Accessibility Accessibility { get; }
    }
}
