using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;

namespace Spectara.Revela.Sdk.Generators;

/// <summary>
/// Exempts code generated by the .NET Configuration Binding Source Generator from the plugin
/// configuration ban (RS0030 with <c>BannedSymbols.RevelaPlugin.txt</c>).
/// </summary>
/// <remarks>
/// <para>
/// Plugins bind their settings with <c>AddOptions&lt;T&gt;().BindConfiguration(T.Section)</c>,
/// which REVELA003 restricts to the plugin's own section. For trim/AOT safety the binding
/// generator replaces that call with generated code that necessarily uses
/// <c>IConfiguration</c>; the banned-API analyzer also inspects generated code and would
/// reject it. Only syntax trees produced by that generator are exempt — identified by the
/// generator assembly folder Roslyn puts in every generated file path — so hand-written plugin
/// code stays banned.
/// </para>
/// </remarks>
[DiagnosticAnalyzer(LanguageNames.CSharp)]
public sealed class ConfigurationBindingSuppressor : DiagnosticSuppressor
{
    /// <summary>Suppression ID for RS0030 in generated configuration binding code.</summary>
    public const string SuppressionId = "REVELASP001";

    private const string BindingGeneratorAssembly = "Microsoft.Extensions.Configuration.Binder.SourceGeneration";

    internal static readonly SuppressionDescriptor GeneratedBinding = new(
        SuppressionId,
        "RS0030",
        "Generated configuration binding code implements a BindConfiguration call that REVELA003 already restricts to the plugin's own section.");

    /// <inheritdoc />
    public override ImmutableArray<SuppressionDescriptor> SupportedSuppressions { get; } = [GeneratedBinding];

    /// <inheritdoc />
    public override void ReportSuppressions(SuppressionAnalysisContext context)
    {
        foreach (var diagnostic in context.ReportedDiagnostics)
        {
            if (IsInGeneratedBindingCode(diagnostic.Location.SourceTree))
            {
                context.ReportSuppression(Suppression.Create(GeneratedBinding, diagnostic));
            }
        }
    }

    private static bool IsInGeneratedBindingCode(SyntaxTree? tree)
    {
        if (tree is null || string.IsNullOrEmpty(tree.FilePath))
        {
            return false;
        }

        foreach (var segment in tree.FilePath.Split('/', '\\'))
        {
            if (string.Equals(segment, BindingGeneratorAssembly, StringComparison.Ordinal))
            {
                return true;
            }
        }

        return false;
    }
}
