using Microsoft.Extensions.Options;

namespace Spectara.Revela.Sdk.Configuration;

/// <summary>
/// Trim/AOT-safe validation of <see cref="GenerateConfig"/>'s annotated settings (encoder effort
/// ranges), generated by the <c>[OptionsValidator]</c> source generator.
/// </summary>
/// <remarks>
/// Runs lazily on first access, so an out-of-range value in project.json fails the build step
/// that reads it and is listed by <c>revela check</c>.
/// </remarks>
[OptionsValidator]
internal sealed partial class GenerateConfigValidator : IValidateOptions<GenerateConfig>;
