using System.Collections.Frozen;
using System.Globalization;
using System.Net;
using System.Text;

namespace Spectara.Revela.Plugins.Serve;

/// <summary>
/// Simple HTTP server for serving static files
/// </summary>
/// <remarks>
/// Uses .NET's built-in HttpListener - no external dependencies required.
/// Implements <see cref="IAsyncDisposable"/> for graceful shutdown of background tasks.
/// </remarks>
internal sealed class StaticFileServer : IAsyncDisposable, IDisposable
{
    private readonly string rootPath;
    private readonly HttpListener listener;
    private readonly Action<string, int>? requestCallback;
    private readonly Lock lifecycleLock = new();
    private readonly HashSet<Task> requestTasks = [];
    private CancellationTokenSource? cts;
    private Task? processingTask;
    private Task? shutdownTask;

    /// <summary>
    /// MIME type mappings for common static file extensions
    /// </summary>
    private static readonly FrozenDictionary<string, string> MimeTypes = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        // HTML/Web
        [".html"] = "text/html; charset=utf-8",
        [".htm"] = "text/html; charset=utf-8",
        [".css"] = "text/css; charset=utf-8",
        [".js"] = "text/javascript; charset=utf-8",
        [".mjs"] = "text/javascript; charset=utf-8",
        [".json"] = "application/json; charset=utf-8",
        [".xml"] = "application/xml; charset=utf-8",

        // Images - Modern formats first
        [".avif"] = "image/avif",
        [".webp"] = "image/webp",
        [".jpg"] = "image/jpeg",
        [".jpeg"] = "image/jpeg",
        [".png"] = "image/png",
        [".gif"] = "image/gif",
        [".svg"] = "image/svg+xml",
        [".ico"] = "image/x-icon",

        // Fonts
        [".woff"] = "font/woff",
        [".woff2"] = "font/woff2",
        [".ttf"] = "font/ttf",
        [".otf"] = "font/otf",
        [".eot"] = "application/vnd.ms-fontobject",

        // Other
        [".txt"] = "text/plain; charset=utf-8",
        [".md"] = "text/markdown; charset=utf-8",
        [".pdf"] = "application/pdf",
        [".zip"] = "application/zip",
        [".map"] = "application/json"
    }.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase);

    private static readonly string[] PreferredEncodings = ["br", "gzip"];

    /// <summary>Error page served for missing files, as generated by <c>generate pages</c>.</summary>
    private const string NotFoundPageFileName = "404.html";

    /// <summary>
    /// Creates a new static file server
    /// </summary>
    /// <param name="rootPath">Root directory to serve files from</param>
    /// <param name="port">Port number to listen on</param>
    /// <param name="requestCallback">Optional callback for each request (path, statusCode)</param>
    public StaticFileServer(string rootPath, int port, Action<string, int>? requestCallback = null)
    {
        this.rootPath = Path.GetFullPath(rootPath);
        this.requestCallback = requestCallback;
        listener = new HttpListener();
        listener.Prefixes.Add(string.Format(CultureInfo.InvariantCulture, "http://localhost:{0}/", port));
    }

    /// <summary>
    /// Start the HTTP server
    /// </summary>
    /// <exception cref="HttpListenerException">Thrown when port is already in use</exception>
    public void Start()
    {
        lock (lifecycleLock)
        {
            ObjectDisposedException.ThrowIf(shutdownTask is not null, this);
            if (listener.IsListening)
            {
                return;
            }

            try
            {
                listener.Start();
            }
            catch
            {
                listener.Close();
                throw;
            }

            cts?.Dispose();
            cts = new CancellationTokenSource();
            var token = cts.Token;
            var acceptLoop = Task.Run(() => ProcessRequestsAsync(token));
            processingTask = processingTask is { IsCompleted: false }
                ? Task.WhenAll(processingTask, acceptLoop)
                : acceptLoop;
        }
    }

    /// <summary>
    /// Stop the HTTP server gracefully
    /// </summary>
    public void Stop()
    {
        lock (lifecycleLock)
        {
            if (cts is null or { IsCancellationRequested: true })
            {
                return;
            }

            cts.Cancel();

            try
            {
                listener.Stop();
            }
            catch (ObjectDisposedException)
            {
                // Already disposed - ignore
            }
        }
    }

    /// <summary>
    /// Process incoming HTTP requests
    /// </summary>
    internal async Task ProcessRequestsAsync(
        CancellationToken cancellationToken,
        Func<HttpListener, Task<HttpListenerContext>>? acceptContextAsync = null)
    {
        while (!cancellationToken.IsCancellationRequested)
        {
            try
            {
                var context = await (acceptContextAsync is null
                    ? listener.GetContextAsync()
                    : acceptContextAsync(listener));
                var requestTask = HandleRequestAsync(context, cancellationToken);
                lock (lifecycleLock)
                {
                    requestTasks.Add(requestTask);
                }

                _ = requestTask.ContinueWith(
                    RemoveCompletedRequest,
                    CancellationToken.None,
                    TaskContinuationOptions.ExecuteSynchronously,
                    TaskScheduler.Default);
            }
            catch (HttpListenerException) when (cancellationToken.IsCancellationRequested)
            {
                // Expected when stopping - listener.Stop() causes GetContextAsync to throw
                break;
            }
            catch (ObjectDisposedException) when (cancellationToken.IsCancellationRequested)
            {
                // Expected when disposing
                break;
            }
            catch (InvalidOperationException) when (cancellationToken.IsCancellationRequested)
            {
                break;
            }
        }
    }

    private void RemoveCompletedRequest(Task requestTask)
    {
        _ = requestTask.Exception;
        lock (lifecycleLock)
        {
            requestTasks.Remove(requestTask);
        }
    }

    /// <summary>
    /// Handle a single HTTP request
    /// </summary>
    private async Task HandleRequestAsync(HttpListenerContext context, CancellationToken cancellationToken)
    {
        var request = context.Request;
        var response = context.Response;
        var isHead = request.HttpMethod.Equals("HEAD", StringComparison.OrdinalIgnoreCase);
        var abortResponse = false;

        try
        {
            if (!isHead && !request.HttpMethod.Equals("GET", StringComparison.OrdinalIgnoreCase))
            {
                response.Headers.Add("Allow", "GET, HEAD");
                SendError(response, 405, "Method Not Allowed");
                requestCallback?.Invoke(request.Url?.LocalPath ?? "/", 405);
                return;
            }

            // Get requested path, default to index.html
            var urlPath = request.Url?.LocalPath ?? "/";
            if (urlPath.EndsWith('/'))
            {
                urlPath += "index.html";
            }

            // Security: Prevent directory traversal attacks.
            if (!TryResolveSafePath(rootPath, urlPath, out var requestedPath))
            {
                SendError(response, 403, "Forbidden", writeBody: !isHead);
                requestCallback?.Invoke(urlPath, 403);
                return;
            }

            // Check if file exists
            if (!File.Exists(requestedPath))
            {
                // Mirror production hosting: serve the generated 404.html (fixed path inside the
                // root, never derived from the request) with a 404 status when it exists.
                var notFoundPage = Path.Combine(rootPath, NotFoundPageFileName);
                if (File.Exists(notFoundPage))
                {
                    await SendFileAsync(request, response, notFoundPage, 404, isHead, () => requestCallback?.Invoke(urlPath, 404), cancellationToken);
                }
                else
                {
                    SendError(response, 404, "Not Found", writeBody: !isHead);
                    requestCallback?.Invoke(urlPath, 404);
                }

                return;
            }

            await SendFileAsync(request, response, requestedPath, 200, isHead, () => requestCallback?.Invoke(urlPath, 200), cancellationToken);
        }
        catch (Exception exception) when (exception is OperationCanceledException || cancellationToken.IsCancellationRequested)
        {
            // Server shutting down during file transfer — expected
            abortResponse = true;
        }
        catch (Exception)
        {
            try
            {
                SendError(response, 500, "Internal Server Error", writeBody: !isHead);
            }
            catch (ObjectDisposedException)
            {
                // Response already closed
            }

            requestCallback?.Invoke(request.Url?.LocalPath ?? "/", 500);
        }
        finally
        {
            try
            {
                if (abortResponse)
                {
                    response.Abort();
                }
                else
                {
                    response.Close();
                }
            }
            catch (ObjectDisposedException)
            {
                // Already closed
            }
        }
    }

    /// <summary>
    /// Writes a file (or its current pre-compressed sibling, when the client accepts it) as the response.
    /// </summary>
    /// <remarks><paramref name="onSent"/> runs before the file stream is released.</remarks>
    private static async Task SendFileAsync(
        HttpListenerRequest request,
        HttpListenerResponse response,
        string filePath,
        int statusCode,
        bool isHead,
        Action onSent,
        CancellationToken cancellationToken)
    {
        var extension = Path.GetExtension(filePath);
        var (servedPath, contentEncoding) = ResolveEncodedPath(filePath, request.Headers["Accept-Encoding"]);

        response.ContentType = GetMimeType(extension);
        response.StatusCode = statusCode;

        if (contentEncoding is not null)
        {
            response.Headers.Add("Content-Encoding", contentEncoding);
        }

        if (IsCurrentEncodedVariant(filePath, ".br") ||
            IsCurrentEncodedVariant(filePath, ".gz"))
        {
            response.Headers.Add("Vary", "Accept-Encoding");
        }

        // Add cache headers for assets (not HTML)
        if (!extension.Equals(".html", StringComparison.OrdinalIgnoreCase) &&
            !extension.Equals(".htm", StringComparison.OrdinalIgnoreCase))
        {
            response.Headers.Add("Cache-Control", "public, max-age=3600");
        }

        await using var fileStream = new FileStream(
            servedPath, FileMode.Open, FileAccess.Read, FileShare.Read,
            bufferSize: 65536, useAsync: true);
        response.ContentLength64 = fileStream.Length;
        if (!isHead)
        {
            await fileStream.CopyToAsync(response.OutputStream, cancellationToken);
        }

        onSent();
    }

    /// <summary>
    /// Send an error response
    /// </summary>
    private static void SendError(
        HttpListenerResponse response,
        int statusCode,
        string message,
        bool writeBody = true)
    {
        response.StatusCode = statusCode;
        response.ContentType = "text/plain; charset=utf-8";
        var content = Encoding.UTF8.GetBytes(message);
        response.ContentLength64 = content.Length;
        if (writeBody)
        {
            response.OutputStream.Write(content);
        }
    }

    /// <summary>
    /// Get MIME type for a file extension
    /// </summary>
    /// <param name="extension">File extension including the dot (e.g., ".html")</param>
    /// <returns>MIME type string</returns>
    public static string GetMimeType(string extension) =>
        MimeTypes.TryGetValue(extension, out var mimeType)
            ? mimeType
            : "application/octet-stream";

    internal static (string path, string? encoding) ResolveEncodedPath(
        string requestedPath,
        string? acceptEncoding)
    {
        if (string.IsNullOrWhiteSpace(acceptEncoding))
        {
            return (requestedPath, null);
        }

        var qualityByEncoding = acceptEncoding
            .Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .Select(ParseEncoding)
            .GroupBy(item => item.encoding, StringComparer.OrdinalIgnoreCase)
            .ToDictionary(
                group => group.Key,
                group => group.Max(item => item.quality),
                StringComparer.OrdinalIgnoreCase);

        string? selectedEncoding = null;
        var selectedQuality = 0d;
        foreach (var encoding in PreferredEncodings)
        {
            var quality = qualityByEncoding.GetValueOrDefault(
                encoding,
                qualityByEncoding.GetValueOrDefault("*"));
            var suffix = encoding.Equals("gzip", StringComparison.Ordinal) ? ".gz" : ".br";
            if (quality > selectedQuality && IsCurrentEncodedVariant(requestedPath, suffix))
            {
                selectedEncoding = encoding;
                selectedQuality = quality;
            }
        }

        if (selectedEncoding is null)
        {
            return (requestedPath, null);
        }

        var selectedSuffix = selectedEncoding.Equals("gzip", StringComparison.Ordinal) ? ".gz" : ".br";
        return (requestedPath + selectedSuffix, selectedEncoding);
    }

    private static bool IsCurrentEncodedVariant(string requestedPath, string suffix)
    {
        var encodedPath = requestedPath + suffix;
        return File.Exists(encodedPath) &&
            File.GetLastWriteTimeUtc(encodedPath) >= File.GetLastWriteTimeUtc(requestedPath);
    }

    private static (string encoding, double quality) ParseEncoding(string value)
    {
        var parts = value.Split(';', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
        var quality = 1d;

        foreach (var parameter in parts.Skip(1))
        {
            if (!parameter.StartsWith("q=", StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            if (!double.TryParse(
                    parameter[2..],
                    NumberStyles.AllowDecimalPoint,
                    CultureInfo.InvariantCulture,
                    out quality))
            {
                quality = 0;
            }
        }

        return (parts[0], Math.Clamp(quality, 0, 1));
    }

    /// <summary>
    /// Resolves a request URL path against a root directory, rejecting any attempt
    /// to escape the root via parent traversal (..), absolute paths, or sibling
    /// directories that share a name prefix with the root.
    /// </summary>
    /// <param name="rootPath">Absolute root directory (already canonicalized).</param>
    /// <param name="urlPath">Decoded URL local path (e.g., "/index.html").</param>
    /// <param name="resolvedPath">The full filesystem path inside the root, when allowed.</param>
    /// <returns><c>true</c> if the path is safely inside <paramref name="rootPath"/>.</returns>
    internal static bool TryResolveSafePath(string rootPath, string urlPath, out string resolvedPath)
    {
        resolvedPath = Path.GetFullPath(Path.Combine(rootPath, urlPath.TrimStart('/')));

        // GetRelativePath returns a path starting with ".." for any escape,
        // and an absolute path when the target lives on a different volume.
        var relative = Path.GetRelativePath(rootPath, resolvedPath);
        if (relative.StartsWith("..", StringComparison.Ordinal)
            || Path.IsPathRooted(relative))
        {
            return false;
        }

        return true;
    }

    /// <inheritdoc />
    public async ValueTask DisposeAsync()
    {
        Task shutdown;
        lock (lifecycleLock)
        {
            if (shutdownTask is null)
            {
                Stop();
                shutdownTask = Task.Run(DrainRequestsAsync);
            }

            shutdown = shutdownTask;
        }

        try
        {
            await shutdown;
        }
        finally
        {
            lock (lifecycleLock)
            {
                cts?.Dispose();
                cts = null;
                listener.Close();
            }
        }
    }

    private async Task DrainRequestsAsync()
    {
        try
        {
            if (processingTask is not null)
            {
                await processingTask;
            }
        }
        finally
        {
            Task[] pendingRequests;
            lock (lifecycleLock)
            {
                pendingRequests = [.. requestTasks];
            }

            await Task.WhenAll(pendingRequests);
        }
    }

    /// <inheritdoc />
    public void Dispose() => Task.Run(async () => await DisposeAsync()).GetAwaiter().GetResult();
}
