using System.CommandLine;

using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

using Spectara.Revela.Plugins.Source.Calendar.Commands;
using Spectara.Revela.Plugins.Source.Calendar.Configuration;
using Spectara.Revela.Plugins.Source.Calendar.Services;
using Spectara.Revela.Sdk.Abstractions;
using Spectara.Revela.Sdk.Hosting;

namespace Spectara.Revela.Plugins.Source.Calendar;

/// <summary>
/// Source plugin for fetching iCal feeds.
/// </summary>
/// <remarks>
/// Downloads .ics files from configured URLs and saves them to the source directory.
/// The Calendar plugin then reads these local files during generation.
/// </remarks>
public sealed class SourceCalendarPlugin : IPlugin
{
    /// <inheritdoc />
    public PackageMetadata Metadata { get; } = new()
    {
        Id = "Spectara.Revela.Plugins.Source.Calendar",
        Name = "Source Calendar",
        Version = PackageVersion.FromAssembly(typeof(SourceCalendarPlugin).Assembly),
        Description = "Fetch iCal feeds for calendar data",
        Author = "Spectara"
    };

    /// <inheritdoc />
    public void ConfigureServices(IServiceCollection services)
    {
        // BindConfiguration must live in user-written source so the .NET
        // Configuration Binding Source Generator can intercept it for trim/AOT.
        // The Section constant is generated by the [RevelaConfig] source generator.
        // No top-level DataAnnotations on SourceCalendarConfig (only on nested
        // FeedConfig items); validation of dictionary values would require
        // [ValidateEnumeratedItems] + nested validator types — out of scope here.
        services.AddOptions<SourceCalendarConfig>()
            .BindConfiguration(SourceCalendarConfig.Section);

        services.AddHttpClient<ICalFetcher>((serviceProvider, client) =>
        {
            client.Timeout = TimeSpan.FromSeconds(30);
            var version = serviceProvider.GetRequiredService<IBuildInfo>().Version;
            client.DefaultRequestHeaders.UserAgent.ParseAdd($"Revela/{version} (Static Site Generator)");
        }).RemoveAllLoggers()
            .ConfigurePrimaryHttpMessageHandler(() => new HttpClientHandler { AllowAutoRedirect = false, UseCookies = false });

        services.TryAddTransient<CalendarFetchCommand>();
    }

    /// <inheritdoc />
    public IEnumerable<CommandDescriptor> GetCommands(IServiceProvider services)
    {
        var fetchCommand = services.GetRequiredService<CalendarFetchCommand>();

        var calendarCommand = new Command("calendar", "iCal feed source");
        calendarCommand.Subcommands.Add(fetchCommand.Create());

        yield return new CommandDescriptor(
            calendarCommand,
            ParentCommand: "source",
            Order: 30);
    }
}
